import {
  AttractionItem,
  CreditCardItem,
  EPayItem,
  FoodItem,
  ItineraryDetail,
  ItineraryItem,
  PromoItem,
} from './types';

const NAGOYA_STATION_MAP_CENTER = '35.170915,136.881537';

export const itineraryData: ItineraryItem[] = [
  { day: 'Day 1', slug: 'day-1-arrival', date: '4/15', weekday: '三', hotel: '機場飯店', theme: '✈️ 抵達', schedule: '晚抵中部國際機場 → 機場飯店 check-in → 超商或機場簡單晚餐', rainBackup: '—', status: '✅ 已訂' },
  { day: 'Day 2', slug: 'day-2-atsuta-osu', date: '4/16', weekday: '四', hotel: '名古屋站飯店', theme: '⛩️ 入城＋商店街', schedule: '熱田神宮 → 大須商店街 → 視體力決定是否上 Sky Promenade 夜景', rainBackup: '大須商店街有頂蓋可照逛；大雨時熱田改排名古屋市科學館', status: '✅ 已訂' },
  { day: 'Day 3', slug: 'day-3-todagawa', date: '4/17', weekday: '五', hotel: '名古屋站飯店', theme: '🌳 親子戶外', schedule: '戶田川綠地公園全天，優先玩空中腳踏車與大型木製遊具', rainBackup: '雨天改名古屋港水族館＋磁浮鐵道館（全室內）', status: '✅ 已訂' },
  { day: 'Day 4', slug: 'day-4-castle-culture', date: '4/18', weekday: '六', hotel: '名古屋站飯店', theme: '🏯 名城文化日', schedule: '名古屋城 → 金鯱橫丁午餐 → 德川園（若時間或體力不足可跳過）', rainBackup: '名古屋城僅逛本丸御殿＋改排名古屋市科學館或豐田產技紀念館', status: '✅ 已訂' },
  { day: 'Day 5', slug: 'day-5-higashiyama', date: '4/19', weekday: '日', hotel: '名古屋站飯店', theme: '🦁 東山動植物園', schedule: '東山動植物園（無尾熊・大象・遊樂園）→ 東山天空塔 → 回飯店', rainBackup: '室內動物館為主（無尾熊館・猿猴館），雨天照常入場', status: '✅ 已訂' },
  { day: 'Day 6', slug: 'day-6-inuyama', date: '4/20', weekday: '一', hotel: '名古屋站飯店', theme: '🏯 犬山城＋城下町', schedule: '名鐵犬山線 → 犬山城天守閣 → 城下町邊走邊吃 → 三光稻荷神社', rainBackup: '天守閣室內不受影響，城下町有騎樓可遮雨，整體影響小', status: '✅ 已訂' },
  { day: 'Day 7', slug: 'day-7-legoland', date: '4/21', weekday: '二', hotel: '榮飯店', theme: '🧱 樂高樂園＋換房', schedule: 'Komeda 早餐 → 退房寄物 → LEGOLAND 熱門設施 → SEA LIFE → 入住榮飯店', rainBackup: '小雨照常；若大雨可縮短戶外設施，改以潛艇冒險、工廠導覽、Bricktopia 與 SEA LIFE 為主', status: '✅ 已訂' },
  { day: 'Day 8', slug: 'day-8-sakae-shopping', date: '4/22', weekday: '三', hotel: '榮飯店', theme: '🛍️ 榮商圈購物＋飛驒牛午餐', schedule: 'PARCO 逛街 → 馬喰一代午餐 → LACHIC → HARBS → Oasis 21', rainBackup: '完全室內購物日，不受天氣影響', status: '✅ 已訂' },
  { day: 'Day 9', slug: 'day-9-ghibli-park', date: '4/23', weekday: '四', hotel: '榮飯店', theme: '🌳 吉卜力公園', schedule: '09:30 抵達園區找彩蛋 → 10:00 魔法之里 → 11:00 大倉庫 → 13:15 魔女之谷', rainBackup: '保留大倉庫與魔女之家等室內點，雨天照常但戶外拍照與排隊時間需機動調整', status: '✅ 已訂' },
  { day: 'Day 10', slug: 'day-10-nagoya-station-shopping', date: '4/24', weekday: '五', hotel: '榮飯店', theme: '🍞 名古屋站採購日', schedule: 'Tsubame Bread & Milk 早餐 → Piyorin → 高島屋 B1 伴手禮 → SUGI 藥局 → 午餐 → 回榮飯店', rainBackup: '—', status: '✅ 已訂' },
  { day: 'Day 11', slug: 'day-11-last-shopping-airport', date: '4/25', weekday: '六', hotel: '機場飯店', theme: '🛍️ 榮／大須最後巡禮＋移動機場', schedule: '行李寄放榮飯店 → 榮商圈補貨 → 大須商店街午餐＋逛逛 → 取行李 → 名鐵移動機場 → FLIGHT OF DREAMS → 機場飯店 check-in', rainBackup: '大須有騎樓與頂蓋，雨天照逛', status: '✅ 已訂' },
  { day: 'Day 12', slug: 'day-12-return', date: '4/26', weekday: '日', hotel: '—', theme: '✈️ 返台', schedule: '機場飯店早餐 → 整理行李 → 辦理登機 → 返台', rainBackup: '—', status: '✅ 已訂' },
];

export const itineraryDetailsData: ItineraryDetail[] = [
  {
    day: 'Day 1',
    slug: 'day-1-arrival',
    title: '深夜抵達',
    date: '4/15',
    weekday: '三',
    theme: '✈️ 深夜抵達',
    intro: '這天唯一任務就是平安抵達、好好睡覺，先把通關、晚餐、入住辦好就好。',
    hotel: '機場飯店',
    breakfast: '—（深夜抵達）',
    status: '✅ 已訂',
    timeline: [
      { time: '晚上抵達', activity: '🛬 入境、提領行李、通關', note: '提前準備好 eSIM 或降落後馬上開通網路' },
      { time: '入境後', activity: '🍙 機場超商買晚餐／宵夜', note: '¥500–1,000，Centrair 機場超商 24 小時' },
      { time: '入境後', activity: '🚶 步行前往機場飯店 check-in', note: '機場飯店走路可達，不用拖著行李搭車' },
    ],
    tips: ['機場飯店入住前先在機場換一些日幣零錢，很多神社、小店不收刷卡。'],
  },
  {
    day: 'Day 2',
    slug: 'day-2-atsuta-osu',
    title: '入城＋大須商店街',
    date: '4/16',
    weekday: '四',
    theme: '⛩️ 入城＋大須商店街',
    intro: '從機場移動進市區，以文化加逛街為主，節奏中等。',
    hotel: '名古屋站飯店',
    breakfast: '🍳 飯店附早餐',
    status: '✅ 已訂',
    timeline: [
      { time: '07:30–08:30', activity: '🍳 飯店早餐', note: '吃飽再搭名鐵進市區' },
      { time: '09:00', activity: '🚆 搭名鐵 μ-SKY 特急 → 名古屋站', note: '¥1,360/人，約 28 分鐘' },
      { time: '09:30–11:30', activity: '⛩️ 熱田神宮', note: '免費（寶物館 ¥500），日本三大神宮之一，氛圍莊嚴' },
      { time: '11:30–12:30', activity: '🍜 午餐：宮きしめん（神宮境內）', note: '¥800–1,200，名古屋名物平麵，境內有店超方便' },
      { time: '13:00–17:30', activity: '🛍️ 大須商店街：扭蛋、二手店、甜點、藥妝', note: '有頂蓋，下雨也能逛' },
      { time: '17:30–18:30', activity: '🏨 回名古屋站飯店 check-in、放行李休息' },
      { time: '20:00–22:00', activity: '🌃 【體力夠】Sky Promenade 夜景（46F）', note: '大人 ¥700、小孩 ¥400，最終入場 22:30' },
    ],
    rainPlan: '熱田神宮改排名古屋市科學館（世界最大天象儀，記得早到搶票）。',
    transport: ['機場 → 名古屋站：名鐵 μ-SKY 特急，¥1,360/人，約 28 分鐘', '名古屋站 → 熱田神宮：地鐵名城線「熱田神宮伝馬町站」約 10 分鐘', '建議入手 manaca 交通 IC 卡或用 Suica，刷卡搭車最方便'],
  },
  {
    day: 'Day 3',
    slug: 'day-3-todagawa',
    title: '戶田川綠地公園',
    date: '4/17',
    weekday: '五',
    theme: '🌳 戶田川綠地公園',
    intro: '今天全天親子戶外，節奏輕鬆。',
    hotel: '名古屋站飯店',
    breakfast: '🍳 飯店附早餐',
    status: '✅ 已訂',
    timeline: [
      { time: '07:30–08:30', activity: '🍳 飯店早餐', note: '吃飽再出發，今天要去公園全天' },
      { time: '08:45', activity: '🚆 名古屋站出發 → JR 春田站 → 公車至戶田川綠地', note: '¥400 左右，轉公車「南陽巡回」，約 35 分鐘' },
      { time: '09:30–12:30', activity: '🌳 戶田川綠地公園前半場：木製遊具、空中腳踏車', note: '入場免費，設施 ¥100–200，東海最大木製遊具' },
      { time: '12:30–13:30', activity: '🧺 公園內野餐 or 便利商店午餐', note: '¥500–1,000，公園內有飲食區，可自備輕食' },
      { time: '13:30–16:30', activity: '🐾 後半場：小動物接觸區、戲水區（4 月視開放）', note: '¥100–200，小孩體力通常撐到這裡剛好' },
      { time: '17:00', activity: '🚆 搭車返回名古屋站' },
      { time: '晚餐', activity: '🐷 矢場とん（味噌豬排）名古屋站分店', note: '¥1,500–2,500，名古屋名物首選' },
    ],
    rainPlan: '改排名古屋港水族館（虎鯨＋海豚秀）＋磁浮鐵道館，兩個都在金城埠頭站，全室內一天排得完。',
    transport: ['名古屋站 → 戶田川綠地：JR 春田站 → 公車「南陽巡回」，約 35 分鐘，¥400 左右'],
    tips: ['4 月開放時間 09:00–18:00，週一公休（週五照常開）。'],
  },
  {
    day: 'Day 4',
    slug: 'day-4-castle-culture',
    title: '名城文化日',
    date: '4/18',
    weekday: '六',
    theme: '🏯 名城文化日',
    intro: '今天以名古屋城與德川園為主，文化感滿點。',
    hotel: '名古屋站飯店',
    breakfast: '🍳 飯店附早餐',
    status: '✅ 已訂',
    timeline: [
      { time: '07:00–08:00', activity: '🍳 飯店早餐', note: '吃飽再出發，今天要早到名古屋城' },
      { time: '08:30', activity: '🚇 地鐵名城線 → 市役所站步行 5 分', note: '¥210' },
      { time: '09:00–12:00', activity: '🏯 名古屋城：本丸御殿＋天守閣外觀', note: '大人 ¥500、小孩免費，本丸御殿室內金碧輝煌，雨天也超值' },
      { time: '12:00–13:30', activity: '🍽️ 午餐：金鯱橫丁', note: '¥1,000–1,500，名古屋城旁，きしめん／味噌串燒都有' },
      { time: '13:30–15:30', activity: '🌸 德川園（步行或短程巴士約 15 分）', note: '大人 ¥300、小孩免費，4 月中旬八重紅枝垂櫻可能還有尾巴' },
      { time: '晚餐', activity: '🍗 風來坊 或 世界山將手羽先', note: '¥1,500–2,000，名古屋手羽先兩大名店，17:00 後開始' },
    ],
    rainPlan: '德川園改排名古屋市科學館（全室內）或豐田產業技術紀念館。',
    transport: ['名古屋站 → 市役所站（地鐵名城線）：約 10 分鐘，¥210', '市役所站 → 德川園：約 15 分鐘，¥210'],
    tips: ['名古屋城開放時間 09:00–16:30（本丸御殿最終入場 16:00）。', '今天是週六，建議開門前 10 分鐘到。'],
  },
  {
    day: 'Day 5',
    slug: 'day-5-higashiyama',
    title: '東山動植物園',
    date: '4/19',
    weekday: '日',
    theme: '🦁 東山動植物園',
    intro: '今天前往東山動植物園，節奏輕鬆，9 點開園直衝無尾熊館。',
    hotel: '名古屋站飯店',
    breakfast: '🍳 飯店附早餐',
    status: '✅ 已訂',
    timeline: [
      { time: '07:00–07:30', activity: '🍳 飯店早餐', note: '今天要早出發，搶開園人潮' },
      { time: '08:30', activity: '🚇 地鐵東山線 → 東山公園站 3 號出口步行 3 分', note: '¥210，約 12 分鐘' },
      {
        time: '09:00–13:00',
        activity: '🦁 東山動植物園',
        note: '開園先衝無尾熊館，再依序走熱門動物區，中午在園內或樹蔭區用餐。',
        details: [
          { time: '09:00', activity: '🎫 開園入場', note: '大人 ¥500（持地鐵一日券折 ¥100 → ¥400）、小孩免費' },
          { time: '09:00–09:30', activity: '🐨 無尾熊館（開園直衝）', note: '人氣第一，早到才不擠' },
          { time: '09:30–11:00', activity: '🦧 夏巴尼猩猩、小貓熊、水獺', note: '小孩最愛的毛茸茸區' },
          { time: '11:00–12:00', activity: '🐘 大象、長頸鹿、北極熊', note: '大型動物區' },
          { time: '12:00–13:00', activity: '🍱 樹蔭野餐 or 園內餐廳午餐', note: '¥800–1,200，建議自備便當，午後座位幾乎滿' },
        ],
      },
      {
        time: '13:00–15:30',
        activity: '🗼 東山天空塔',
        note: '下午先玩遊樂園，再登天空塔，最後逛紀念品店或自由活動。',
        details: [
          { time: '13:00–14:00', activity: '🎠 遊樂園設施', note: '天鵝船 ¥1,600／4 人、斜坡射手 ¥360／人，4 歲最愛' },
          { time: '14:00–14:30', activity: '🗼 東山天空塔登塔', note: '加購 ¥140，俯瞰名古屋市區' },
          { time: '14:30–15:30', activity: '🛍️ 紀念品店 / 自由活動', note: '出口旁紀念品 ¥300 起，也可補逛喜歡的區域' },
        ],
      },
      { time: '15:30', activity: '🚇 搭地鐵返回名古屋站', note: '¥210' },
      { time: '晚餐', activity: '🍗 風來坊手羽先（名古屋站附近）', note: '¥1,500–2,000，今天輕鬆走，晚餐吃名古屋名物' },
    ],
    rainPlan: '室內動物館為主（無尾熊館・猿猴館），雨天照常入場，遊樂設施視情況暫停。',
    transport: ['名古屋站 → 東山公園站（地鐵東山線）：約 12 分鐘，¥210'],
    tips: ['週日人潮比平日多，建議 09:00 開園就進去，最擁擠時段為 11:00–15:00。'],
  },
  {
    day: 'Day 6',
    slug: 'day-6-inuyama',
    title: '犬山城＋城下町',
    date: '4/20',
    weekday: '一',
    theme: '🏯 犬山城＋城下町',
    intro: '今天前往犬山，登日本最古老天守閣＋城下町邊走邊吃，平日人潮也較輕鬆。',
    hotel: '名古屋站飯店',
    breakfast: '🍳 飯店附早餐',
    status: '✅ 已訂',
    timeline: [
      { time: '07:30–08:30', activity: '🍳 飯店早餐', note: '吃飽再出發' },
      { time: '09:00', activity: '🚆 名古屋站 → 名鐵犬山線特急 → 犬山站', note: '¥570／人，約 30 分鐘' },
      { time: '09:30–11:00', activity: '🏯 犬山城天守閣登閣', note: '大人 ¥1,000、小孩 ¥200，日本現存最古老天守閣，頂樓視野絕佳' },
      { time: '11:00–13:00', activity: '🚶 城下町本町通り邊走邊吃', note: '恋小町だんご ¥400／飛驒牛握壽司 ¥800／生麩蜂蜜蛋糕 ¥400／五平餅 ¥300' },
      { time: '13:00–14:00', activity: '🍜 城下町內午餐（壽俵屋或うどん）', note: '¥1,000–1,500' },
      { time: '14:00–14:45', activity: '⛩️ 三光稻荷神社（心形繪馬牆打卡）', note: '免費，步行 5 分' },
      { time: '15:00', activity: '🚆 犬山站搭名鐵返回名古屋站', note: '¥570／人，約 30 分鐘' },
      { time: '15:30', activity: '🧳 回飯店休息、整理行李（明天退房換榮飯店）', note: '趁今晚把行李整理好，明天退房順暢' },
      { time: '晚餐', activity: '🐷 矢場とん（名古屋站店）味噌豬排', note: '¥1,500–2,500，今天走路多，吃頓好的犒賞' },
    ],
    rainPlan: '天守閣室內不受影響，城下町有騎樓可遮雨，整體影響小。',
    transport: ['名古屋站 → 犬山站（名鐵犬山線特急）：約 30 分鐘，¥570'],
    tips: ['犬山城全年只有 12/29–31 公休，週一完全沒問題。'],
  },
  {
    day: 'Day 7',
    slug: 'day-7-legoland',
    title: '樂高樂園＋換房',
    date: '4/21',
    weekday: '二',
    theme: '🧱 樂高樂園＋換房',
    intro: '週二人潮相對少，適合一開園就先衝熱門設施；這天也是換房日，回程要順手取行李前往榮。',
    hotel: '榮飯店',
    breakfast: '☕ Komeda 珈琲早餐',
    status: '✅ 已訂',
    timeline: [
      { time: '07:30–08:30', activity: '☕ Komeda 珈琲早餐', note: '先吃飽再出發，今天走整天；點飲料通常附厚片土司' },
      { time: '08:30', activity: '🧳 名古屋站飯店退房，行李寄放置物櫃或飯店', note: '建議早點寄物，傍晚回名古屋站取件後再前往榮飯店' },
      { time: '08:45', activity: '🚆 名古屋站 → 青波線 → 金城埠頭站', note: '¥570，車程約 24 分鐘' },
      { time: '09:30', activity: '🚪 抵達入口排隊，先打開官方 App 看即時等待時間', note: '園區 10:00 開園，今天營業到 17:00' },
      {
        time: '10:00–11:30',
        activity: '🔴 第一波：熱門設施先衝',
        note: '開園先把最容易塞車的設施玩掉，避免下午排隊過長。',
        details: [
          { time: '10:00', activity: '🐉 飛龍 The Dragon', note: '開園先衝熱門設施；105cm 可搭，未滿 120cm 需大人陪同' },
          { time: '10:30', activity: '🔫 失落王國探險', note: '室內射擊闖關，接在飛龍後面排隊最順' },
          { time: '11:00', activity: '🚢 潛艇冒險', note: '全家都能搭，室內也能順便避太陽' },
        ],
      },
      {
        time: '11:30–13:00',
        activity: '🟡 第二波：Ninjago 區＋提早午餐',
        note: '先玩一項 Ninjago 設施，再趁 11:30 左右避開餐廳尖峰。',
        details: [
          { time: '11:30', activity: '🥷 凱的空中射擊', note: 'Ninjago 區人氣設施，5 歲小孩通常會很愛' },
          { time: '11:30–12:10', activity: '🍔 提早午餐：Brick House Burger', note: '建議 11:30 左右就吃，避開中午排隊高峰；套餐約 ¥1,700' },
        ],
      },
      {
        time: '13:00–15:00',
        activity: '🟢 第三波：親子互動與玩水設施',
        note: '把年齡限制與容易玩濕的設施放在下午，動線最順。',
        details: [
          { time: '13:00', activity: '🏎️ 初級駕駛學校', note: '3–5 歲限定，這個年齡帶務必優先排進去' },
          { time: '13:30', activity: '🚒 消防學院', note: '踩踏板＋拉水管任務，容易玩到濕' },
          { time: '14:00', activity: '🌊 水花大戰 Splash Battle', note: '午後最適合玩水，先把換洗衣物準備好' },
          { time: '14:30', activity: '🌊 魷魚衝浪', note: '100–120cm 需陪同，接著玩 Ninjago 區動線最順' },
        ],
      },
      {
        time: '15:00–16:30',
        activity: '🔵 第四波：收尾、拍照與購物',
        note: '最後用室內／輕鬆行程收尾，並把購物放在閉園前完成。',
        details: [
          { time: '15:00', activity: '🏭 工廠導覽', note: '記得拿名古屋限定積木' },
          { time: '15:30', activity: '🌏 Miniland', note: '邊走邊拍照，順便找春季限定裝置與迷你大阪新展示' },
          { time: '15:50', activity: '🧱 Bricktopia 自由建造', note: '讓小孩放電收尾，爸媽也能稍微休息' },
          { time: '16:00', activity: '🛍️ The Big Shop 購物', note: '17:00 閉園前先買，熱門限定款不要拖到最後一刻' },
        ],
      },
      { time: '16:30–17:30', activity: '🐟 SEA LIFE 水族館', note: '樂高 17:00 閉園後無縫接續；成人 ¥2,200、兒童 ¥1,100，18:30 前都可逛' },
      { time: '17:30', activity: '🚆 搭青波線返回名古屋站，取行李 → 地鐵前往榮飯店 check-in', note: '回程車資 ¥570' },
      { time: '晚餐', activity: '🍜 麵家獅子丸（台灣拉麵）', note: '¥900–1,200，若玩太累也可改在榮附近簡單吃' },
    ],
    rainPlan: '若遇大雨，優先保留潛艇冒險、失落王國探險、工廠導覽、Bricktopia 與 SEA LIFE，水花大戰等會濕或露天設施視現場狀況刪減。',
    transport: ['名古屋站 → 金城埠頭（青波線）：約 24 分鐘，¥570', '金城埠頭 → 名古屋站（青波線）：約 24 分鐘，¥570'],
    tips: ['4/21（週二）LEGOLAND 營業時間是 10:00–17:00，SEA LIFE 為 10:00–18:30。', '園內禁止攜帶外食（嬰兒副食品除外），午餐直接安排園內吃最省時間。', '初級駕駛學校限 3–5 歲，若現場需要可出示護照確認年齡。', '春季活動期間可留意櫻花樹裝置、Flower Garden、限定遊行與角色互動時間表。'],
  },
  {
    day: 'Day 8',
    slug: 'day-8-sakae-shopping',
    title: '榮商圈購物日＋飛驒牛午餐',
    date: '4/22',
    weekday: '三',
    theme: '🛍️ 榮商圈購物日＋飛驒牛午餐',
    intro: '今天純購物＋飛驒牛午餐，完全室內，天氣再差都不怕。',
    hotel: '榮飯店',
    breakfast: '🥪 外食（Komeda 珈琲推薦）',
    status: '✅ 已訂',
    timeline: [
      { time: '08:30–09:30', activity: '🥪 Komeda 珈琲或超商早餐', note: '今天不用趕，睡飽再出門' },
      { time: '10:00–12:00', activity: '🛍️ PARCO 百貨（矢場町站）：吉伊卡哇、潮牌、玩具', note: '10:00 開門，人少時搶先逛' },
      { time: '12:00–13:30', activity: '🥩 飛驒牛一頭家 馬喰一代 名古屋栄【已預約】', note: '✅ 大人 2 名＋小孩 1 名，用餐到 13:30，榮商圈步行可達' },
      { time: '13:30–15:30', activity: '🛍️ LACHIC＋松坂屋', note: 'LACHIC 11:00–21:00，女裝、雜貨豐富' },
      { time: '15:30–16:30', activity: '🍰 HARBS 水果千層蛋糕下午茶', note: '¥1,000–1,500，平日下午排隊短，好時機' },
      { time: '16:30–18:00', activity: '📸 綠洲 21（Oasis 21）拍照＋MainLabo 扭蛋掃貨', note: '免費入場，傍晚燈光很美' },
      { time: '晚餐', activity: '🍗 世界山將 或 風來坊手羽先', note: '¥1,500–2,000，午餐吃飛驒牛，晚上輕食手羽先剛剛好' },
      { time: '飯後', activity: '🌙 榮商圈夜逛、唐吉訶德採購日用品', note: '唐吉訶德深夜營業，補貨好時機' },
    ],
    tips: ['榮商圈動線建議：矢場町站下車 → PARCO → 午餐燒肉 → LACHIC → 三越 → 綠洲 21，全程步行可達。'],
  },
  {
    day: 'Day 9',
    slug: 'day-9-ghibli-park',
    title: '吉卜力公園全天',
    date: '4/23',
    weekday: '四',
    theme: '🌳 吉卜力公園全天',
    intro: '今天依 4/23 最終版動線走：先在免費區找彩蛋，再依序進魔法之里、大倉庫與魔女之谷，把限量兌換券與熱門設施放前面。',
    hotel: '榮飯店',
    breakfast: '🥪 外食（超商／咖啡廳）',
    status: '✅ 已訂',
    timeline: [
      { time: '07:30–08:15', activity: '🥪 早餐', note: '先吃超商或咖啡廳早餐，吃完直接出發前往吉卜力公園' },
      { time: '08:35–09:30', activity: '🚇 榮 → 藤丘 → 愛・地球博紀念公園', note: '搭地鐵東山線轉 Linimo，到站後步行約 10 分鐘進園區' },
      { time: '09:30–09:55', activity: '🏞️ 免費區域', note: '先在園區步道散步，找「吉卜力遺失物品」15 個隱藏彩蛋' },
      {
        time: '10:00–10:45',
        activity: '🌿 魔法之里',
        note: '優先看邪魔神雕像、乙事主溜滑梯與達達拉城外觀，時間夠可加五平餅',
        details: [
          { time: '10:00', activity: '🎫 進入魔法之里（掃票，只能進一次）', note: '10:00 開門，早進人最少' },
          { time: '10:00–10:45', activity: '👀 依序看邪魔神雕像、乙事主溜滑梯、達達拉城外觀', note: '若還有空檔可加五平餅體驗' },
          { time: '10:50', activity: '🚶 步行前往大倉庫入口待機', note: '魔法之里 → 大倉庫步行約 5 分鐘' },
        ],
      },
      {
        time: '11:00–13:00',
        activity: '🏢 大倉庫',
        note: '先拍無臉男，再逛名場面展示區、艾莉緹房間、短片電影院、天空之城機器人與紀念品店',
        details: [
          { time: '11:00', activity: '🎫 吉卜力大倉庫準時掃票入場（只能進一次）', note: '記得出示護照核對實名' },
          { time: '11:05', activity: '📸 先去無臉男拍照區排隊', note: '開場人最少，通常比下午少很多' },
          { time: '11:20', activity: '🎬 名場面展示區（千尋湯屋、龍貓公車站等）', note: '超好拍，可多留一點時間' },
          { time: '11:45', activity: '🏠 艾莉緹借物小人縮小房間', note: '視覺效果很強，列為必看' },
          { time: '12:00', activity: '🎞️ 免費電影院「獵戶座」短片', note: '約 15 分鐘，先確認場次時間' },
          { time: '12:20', activity: '🤖 二樓天空之城機器人景觀窗拍照', note: '若還有時間可順看二樓靜態動畫原稿展' },
          { time: '12:40', activity: '🛍️ 紀念品店「冒險飛行團」掃貨', note: '限定商品易售完，建議此時買好' },
          { time: '13:00', activity: '🚶 離開大倉庫，步行前往魔女之谷', note: '步行約 10–15 分鐘' },
        ],
      },
      {
        time: '13:15–17:00',
        activity: '🧙‍♀️ 魔女之谷',
        note: '先領霍爾城堡兌換券，再排飛行烤箱與加購票，接著逛魔女之家、霍爾城堡與蕪菁拍照',
        details: [
          { time: '13:15', activity: '🎫 進入魔女之谷（掃票，只能進一次）', note: '進去後第一件事先去霍爾城堡領整理兌換券' },
          { time: '13:15', activity: '🎟️ 霍爾城堡附近領整理兌換券，確認指定入場時間', note: '第一優先，限量發放，確認時間後再安排後續' },
          { time: '13:25', activity: '🍽️ 飛行烤箱排隊吃午餐', note: '全園人氣最高，可能等 20–40 分鐘，可考慮牧羊人派或炸魚薯條' },
          { time: '14:00', activity: '🎟️ 排隊購買當日加購票（第二輪開賣）', note: '霍爾 ¥1,000、琪琪的家 ¥400、魔女之家 ¥400' },
          { time: '14:10', activity: '🧙 進入魔女之家', note: '安雅與魔女主題，約 20 分鐘，廚房與房間都很值得看' },
          { time: '14:35', activity: '🏠 進入歐其諾宅邸（琪琪的家）', note: '約 15 分鐘，時間有限可快速逛' },
          { time: '15:00', activity: '🏰 依兌換券指定時間進入霍爾的移動城堡', note: '約 25 分鐘，可看卡西法壁爐與霍爾房間彩蛋' },
          { time: '15:30', activity: '📸 魔女之谷自由拍照與點心', note: '可補拍古古羅斯麵包店、Hot Tin Roof 與旋轉木馬' },
          { time: '16:30', activity: '📸 稻草人蕪菁拍照區排隊', note: '16:30 後通常比白天快很多，這時再排最划算' },
          { time: '16:45', activity: '🛍️ 最後衝紀念品店「13人的魔女團」', note: '補買魔女之谷限定商品' },
        ],
      },
      { time: '17:00–17:50', activity: '🚇 回程交通', note: '閉園後搭 Linimo 回藤丘，再轉地鐵東山線回榮' },
      { time: '晚餐', activity: '🍽️ 榮周邊自選', note: '回市區後找順路餐廳輕鬆吃，今天行程滿，晚餐彈性安排即可' },
    ],
    rainPlan: '雨天照常進行，優先保留大倉庫、電影院、魔女之家、琪琪的家與霍爾城堡；戶外彩蛋、蕪菁拍照與街景拍攝則依雨勢機動調整停留時間。',
    transport: ['榮 → 藤丘（地鐵東山線）→ 愛・地球博紀念公園（Linimo）：單程約 50 分鐘', '愛・地球博紀念公園站 → 園區入口：步行約 10 分鐘', '魔法之里 → 大倉庫：約 5 分鐘步行；大倉庫 → 魔女之谷：約 10–15 分鐘步行'],
    tips: ['三個付費區域都只能依票券指定方式進場一次，移動前先確認是否已逛完。', '魔女之谷入園後先領霍爾城堡整理兌換券，再排午餐與加購票。', '稻草人蕪菁建議 16:30 後再排，通常比白天省時很多。'],
  },
  {
    day: 'Day 10',
    slug: 'day-10-nagoya-station-shopping',
    title: '名古屋站採購日',
    date: '4/24',
    weekday: '五',
    theme: '🍞 名古屋站採購日',
    intro: '早上吃 Tsubame 早餐，接著衝名古屋站伴手禮，晚上回榮飯店。',
    hotel: '榮飯店',
    breakfast: '🍞 Tsubame Bread & Milk（外食）',
    status: '✅ 已訂',
    timeline: [
      { time: '07:30–08:00', activity: '🍞 Tsubame Bread & Milk 早餐（つばめパン＆Milk 名駅店）', note: '名古屋站步行 5 分，08:00 開門，¥500–1,000，只收現金／PayPay，不收信用卡' },
      { time: '09:00–09:30', activity: '🐥 Piyorin 小雞蛋糕（廣小路口，09:00 開賣）', note: '¥500–700／個，名古屋站限定，賣完就沒' },
      { time: '09:30–11:30', activity: '🎁 JR Gate Tower 高島屋 B1 伴手禮街掃貨', note: '青蛙饅頭、蝦餅、名古屋土產一次買齊' },
      { time: '11:30–12:30', activity: '💊 藥妝決戰：SUGI 藥局（名古屋站旁）', note: '兩層樓規模，化妝品、藥品、食品通通有' },
      { time: '12:30–13:30', activity: '🍽️ 午餐：矢場とん（名古屋站店）or 站內美食街', note: '¥1,500–2,500' },
      { time: '13:30 以後', activity: '🧳 回榮飯店休息・整理戰利品', note: '明天輕裝出發' },
    ],
    tips: ['今天是週五，名古屋站人潮相對少，Piyorin 早到不用排太久。', '伴手禮採購優先順序：① Piyorin ② 青蛙饅頭 ③ 蝦餅 ④ 藥妝 ⑤ 高島屋 B1。'],
  },
  {
    day: 'Day 11',
    slug: 'day-11-last-shopping-airport',
    title: '榮／大須最後巡禮＋移動機場',
    date: '4/25',
    weekday: '六',
    theme: '🛍️ 榮／大須最後巡禮＋移動機場',
    intro: '行李寄放榮飯店後輕裝出發，傍晚取行李移動機場，抵達後逛 FLIGHT OF DREAMS。',
    hotel: '機場飯店',
    breakfast: '🥪 外食（超商／咖啡廳）',
    status: '✅ 已訂',
    timeline: [
      { time: '07:30–08:30', activity: '🥪 超商或咖啡廳早餐', note: '吃完回飯店整理行李準備寄放' },
      { time: '09:00', activity: '🧳 榮飯店寄放行李', note: '輕裝出發，傍晚取行李' },
      { time: '09:30–12:00', activity: '🛍️ 榮商圈補貨：藥妝、唐吉訶德、扭蛋、三越', note: '昨天採購完伴手禮，今天買日用品和零食' },
      { time: '12:00–13:30', activity: '🍽️ 大須商店街午餐＋最後逛逛', note: '¥900–1,500，步行約 15 分，補買沒買到的東西' },
      { time: '13:30–15:30', activity: '⛩️ 【視體力】大須觀音參拜＋古著掃貨 or 回榮咖啡廳休息', note: '走累了就找咖啡廳坐著等' },
      { time: '16:00', activity: '🧳 回榮飯店取行李' },
      { time: '16:30', activity: '🚇 地鐵榮 → 名古屋站 → 名鐵 μ-SKY 特急 → 中部國際機場', note: '¥210 + ¥1,360，約 40 分鐘' },
      { time: '17:30', activity: '🏨 機場飯店 check-in・放行李', note: '先放好行李輕鬆逛' },
      { time: '18:00–19:30', activity: '✈️ FLIGHT OF DREAMS（波音 787 博物館）', note: '免費入場，波音客機展示，小孩超愛' },
      { time: '晚餐', activity: '🍽️ 機場 4F 藍天城 Sky Town 自選', note: '多家選擇，輕鬆吃' },
      { time: '飯後', activity: '🛍️ 機場免稅店補貨、整理行李', note: '明早航班前 2.5 小時到報到' },
    ],
    transport: ['榮 → 名古屋站（地鐵）：¥210，約 5 分鐘', '名古屋站 → 中部國際機場（名鐵 μ-SKY 特急）：¥1,360，約 28 分鐘'],
    tips: ['今天是週六，大須商店街人潮較多，建議午餐前到。'],
  },
  {
    day: 'Day 12',
    slug: 'day-12-return',
    title: '返台',
    date: '4/26',
    weekday: '日',
    theme: '✈️ 返台',
    intro: '帶著滿滿回憶，平安返家。',
    hotel: '—',
    breakfast: '🍳 機場飯店附早餐',
    status: '✅ 已訂',
    timeline: [
      { time: '早起', activity: '🍳 機場飯店早餐後整理行李、確認護照票券', note: '建議航班起飛前 2.5 小時到達報到' },
      { time: '候機前', activity: '🛍️ 機場免稅店掃貨＋買天むす緋毬飯糰帶上飛機', note: '飯糰買來在飛機上吃超幸福' },
      { time: '登機時間', activity: '🛫 起飛！返台', note: '帶著滿滿回憶和行李返家 🏠' },
    ],
    tips: ['回台前確認 manaca 卡餘額可在機場退費。', '藥妝、食品超過限額記得分裝托運。'],
  },
];

export const itineraryDetailMap = Object.fromEntries(
  itineraryDetailsData.map((detail) => [detail.day, detail]),
) as Record<string, ItineraryDetail>;

export const foodData: FoodItem[] = [
  { name: '艾許奶油泡芙（ÉCLAIR / エシレ）', type: '甜點・早餐', categories: ['早餐', '甜點'], location: '名古屋站', mapQuery: 'エシレ', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day2–Day6 任一早晨出發前', hours: '約09:00開賣', reservation: '❌ 現場排隊', price: '¥400–600/個', notes: '必買！開賣就要去排，假日排隊更長' },
  { name: 'KONPARU 炸蝦三明治', type: '早餐', categories: ['早餐', '名古屋名物'], location: '名古屋站', mapQuery: 'KONPARU', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day2–Day6 任一早晨', hours: '07:00起', reservation: '❌', price: '¥500左右', notes: '名古屋站老牌早餐名店' },
  { name: '天むす緋毬（天婦羅飯糰）', type: '早餐・輕食', categories: ['早餐', '名古屋名物'], location: '名古屋站附近', mapQuery: '天むす緋毬', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day2–Day6 任一早晨', hours: '09:00起', reservation: '❌', price: '¥800左右', notes: '名古屋名物天婦羅飯糰' },
  { name: '名古 onimaru 飯糰', type: '早餐', categories: ['早餐'], location: '名古屋站', mapQuery: 'onimaru', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day2–Day6 任一早晨', hours: '07:00起', reservation: '❌', price: '¥200–400/個', notes: '在地人氣早餐飯糰' },
  { name: 'Tsubame Bread & Milk（つばめパン＆Milk 名駅店）', type: '早餐・麵包', categories: ['早餐'], location: '名古屋站步行5分', mapQuery: 'つばめパン＆Milk 名駅店', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day10（4/24）早餐', hours: '08:00–20:00（Morning 08:00–11:00）', reservation: '❌ 現場排隊', price: '¥500–1,000/人', notes: '100%北海道美瑛小麥天然酵母吐司・⚠️只收現金／PayPay 不收信用卡・Morning 套餐11點後漲價' },
  { name: '飛驒牛一頭家 馬喰一代 名古屋栄', type: '午餐・燒肉', categories: ['正餐'], location: '榮商圈（栄）', mapQuery: '馬喰一代 名古屋栄', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day8（4/22）12:00–13:30', hours: '12:00–13:30（已預約）', reservation: '✅ 已預約', price: '¥5000–8000/人', notes: '✅ 大人 2 名＋小孩 1 名・用餐到 13:30' },
  { name: '矢場とん（矢場豬排）', type: '晚餐・名古屋名物', categories: ['正餐', '名古屋名物'], location: '榮／矢場町', mapQuery: '矢場とん', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day9（4/23）或Day10（4/24）', hours: '11:00–21:00', reservation: '⚠️ 假日排隊，建議平日或提早', price: '¥1500–2500', notes: '名古屋味噌豬排最代表性老店，必吃' },
  { name: '風來坊（手羽先）', type: '晚餐・宵夜', categories: ['正餐', '名古屋名物'], location: '名古屋市各處', mapQuery: '風来坊', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day11（4/25）大須日', hours: '17:00–23:00左右', reservation: '❌ 不需要', price: '¥1500–2000', notes: '名古屋手羽先兩大名店之一' },
  { name: '世界山將（手羽先）', type: '晚餐・宵夜', categories: ['正餐', '名古屋名物'], location: '榮附近', mapQuery: '世界の山ちゃん', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day8（4/22）晚餐', hours: '17:00–23:00', reservation: '❌ 不需要', price: '¥1500–2000', notes: '名古屋手羽先兩大名店之一，和風來坊各有擁護者' },
  { name: '麵家獅子丸', type: '晚餐・拉麵', categories: ['正餐'], location: '名古屋站附近', mapQuery: '麺家獅子丸', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day7（4/21）樂高結束後', hours: '11:00–22:00', reservation: '❌', price: '¥900–1200', notes: '名古屋台灣拉麵系統，辣味特色' },
  { name: 'HARBS', type: '甜點・下午茶', categories: ['甜點'], location: '榮商圈', mapQuery: 'HARBS', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day8（4/22）榮購物日', hours: '11:00–20:00', reservation: '⚠️ 假日排隊長', price: '¥1000–1500', notes: '水果千層蛋糕名店，榮店位置很方便' },
  { name: 'Aunt Stella', type: '甜點・伴手禮', categories: ['甜點', '伴手禮'], location: '名古屋站／榮商圈', mapQuery: 'ステラおばさんのクッキー 名古屋', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day5（4/19）東山動物園後順路', hours: '依分店與百貨營業時間', reservation: '❌ 現場購買', price: '¥500–2000/盒', notes: '日本知名手工餅乾品牌・可依動線選名古屋站或榮商圈分店・有些門市可看到現場烘焙・台灣也有但日本買更划算' },
  { name: 'Piyorin 小雞蛋糕', type: '甜點・伴手禮', categories: ['甜點', '伴手禮'], location: '名古屋站（JR名古屋高島屋B1）', mapQuery: 'ぴよりん', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day10（4/24）名古屋站採購日', hours: '依百貨時間', reservation: '❌ 現場購買', price: '¥500–700/個', notes: '名古屋站限定必買！黃色小雞造型超可愛，賣完就沒了要早去' },
  { name: 'えびせんべいの里（蝦餅）', type: '伴手禮', categories: ['伴手禮'], location: '名古屋站或機場', mapQuery: 'えびせんべいの里', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day10（4/24）採買日', hours: '依店面', reservation: '❌', price: '¥1000–2000/盒', notes: '名古屋知名伴手禮，蝦餅系列多種口味' },
  { name: '機場鰻魚飯', type: '午餐・機場美食', categories: ['正餐', '名古屋名物'], location: '中部國際機場（Centrair）', mapQuery: '中部国際空港 うなぎ', mapCenter: NAGOYA_STATION_MAP_CENTER, suggestedDay: 'Day12（4/26）返台當天', hours: '機場營業時間', reservation: '❌', price: '¥2000–3500', notes: '離開前最後一餐，機場內有多家鰻魚飯店' },
];

export const attractionData: AttractionItem[] = [
  { name: '吉卜力公園', type: '主題公園', categories: ['親子必去', '郊區一日遊'], location: '愛知縣長久手市', mapQuery: '35.1750449,137.0887689', transport: '地鐵東山線→リニモ', hours: '10:00–18:00（週二休）', cost: '¥2000–5000（依票種）', reservation: '✅ 強烈建議現在就買', familyFriendly: '⭐⭐⭐', rainFriendly: '⚠️ 大倉庫室內OK，戶外園區遇雨體驗下降', weekendFriendly: '✅ 假日OK（需對應票種）', notes: '大倉庫雨天首選，Dondoko之森晴天更適合' },
  { name: '日本樂高樂園', type: '主題樂園', categories: ['親子必去'], location: '名古屋市港區金城埠頭', mapQuery: '35.0506065,136.8438293', transport: '青波線 金城埠頭站 步行5分', hours: '10:00–17:00（4/21 平日）', cost: '大人¥5200、小孩¥3800起', reservation: '✅ 提前購票較便宜', familyFriendly: '⭐⭐⭐', rainFriendly: '⚠️ 戶外設施多，部分雨天暫停', weekendFriendly: '⚠️ 假日擁擠，建議平日', notes: '4/21 平日為 10:00–17:00；必玩可先抓 The Dragon、初級駕駛學校、Miniland 與 The Big Shop' },
  { name: 'Sky Promenade', type: '觀景台・夜景', categories: ['經典景點', '夜景／拍照'], location: '名古屋站直結（JR Gate Tower頂樓）', mapQuery: '35.1704593,136.8851422', transport: '名古屋站步行0分', hours: '11:00–23:00（最終入場22:30）', cost: '大人¥700、小孩¥400', reservation: '❌', familyFriendly: '⭐⭐⭐', rainFriendly: '✅ 室內觀景台（附戶外露台）', weekendFriendly: '⚠️ 假日夜晚人多但不擁擠', notes: '名古屋高樓夜景代表，可遠眺市景' },
  { name: '名古屋城', type: '城堡・歷史', categories: ['經典景點', '夜景／拍照'], location: '名古屋市中區', mapQuery: '35.1847501,136.8996883', transport: '地鐵名城線 市役所站 步行5分', hours: '09:00–16:30（週一休）', cost: '大人¥500', reservation: '❌', familyFriendly: '⭐⭐', rainFriendly: '⚠️ 部分露天，本丸御殿室內OK', weekendFriendly: '⚠️ 假日人多但OK', notes: '本丸御殿室內雨天可參觀' },
  { name: '德川園', type: '日本庭園', categories: ['經典景點', '夜景／拍照'], location: '名古屋市東區', mapQuery: '35.1842918,136.9321824', transport: 'JR／地鐵大曾根站 步行10分', hours: '09:30–17:30（週一休）', cost: '大人¥300、小孩免費', reservation: '❌', familyFriendly: '⭐⭐', rainFriendly: '❌ 露天庭園，雨天不適合', weekendFriendly: '✅ 假日人不多，悠閒', notes: '春天賞花很美，適合搭配名古屋城或德川美術館' },
  { name: '戶田川綠地公園', type: '公園・戶外・親子', categories: ['親子必去'], location: '名古屋市港區', mapQuery: '35.117596,136.8113142', transport: '近鐵 戶田站 步行10分', hours: '09:00–17:00（週一休）', cost: '免費（部分設施¥100–200）', reservation: '❌', familyFriendly: '⭐⭐⭐', rainFriendly: '❌ 戶外公園，雨天不適合', weekendFriendly: '✅ 假日OK，人少悠閒', notes: '大型遊具與草地空間很適合親子放電' },
  { name: '東山動植物園', type: '動物園・植物園', categories: ['動物／水族館'], location: '名古屋市千種區', mapQuery: '35.1565379,136.9818099', transport: '地鐵東山線 東山公園站 步行3分', hours: '09:00–16:50（週一休）', cost: '大人¥500、小孩免費', reservation: '❌', familyFriendly: '⭐⭐⭐', rainFriendly: '⚠️ 戶外為主，下雨體驗差', weekendFriendly: '⚠️ 假日很擁擠，建議平日', notes: '無尾熊展區人氣很高，腹地也大' },
  { name: '綠洲21', type: '地標・夜景', categories: ['經典景點', '夜景／拍照'], location: '榮站旁', mapQuery: '35.1711148,136.9094757', transport: '地鐵榮站步行1分', hours: '10:00–22:00', cost: '免費', reservation: '❌', familyFriendly: '⭐⭐⭐', rainFriendly: '⚠️ 玻璃屋頂下雨另有風味但濕滑', weekendFriendly: '✅ 假日OK，夜晚人較少', notes: '可搭配榮商圈與電視塔周邊一起逛' },
  { name: '熱田神宮', type: '神社・文化', categories: ['經典景點'], location: '名古屋市熱田區', mapQuery: '35.1273579,136.9086948', transport: '地鐵名城線 熱田神宮伝馬町站 步行3分', hours: '境內終日開放', cost: '免費（寶物館¥500）', reservation: '❌', familyFriendly: '⭐⭐', rainFriendly: '⚠️ 境內露天，下雨體驗差', weekendFriendly: '⚠️ 假日人多，氣氛還是好', notes: '日本三大神宮之一，參道很有氛圍' },
  { name: '大須商店街／大須觀音通', type: '商店街・購物・美食', categories: ['購物採買'], location: '名古屋市中區大須', mapQuery: '35.1593823,136.901052', transport: '地鐵鶴舞線 大須觀音站 步行3分', hours: '依各店面', cost: '免費（消費另計）', reservation: '❌', familyFriendly: '⭐⭐', rainFriendly: '⚠️ 有頂蓋路段但非全室內', weekendFriendly: '⚠️ 假日人潮多但很熱鬧', notes: '適合安排小吃、藥妝、二手店與伴手禮採買' },
  { name: '榮商圈／榮地下街', type: '購物・地下街', categories: ['購物採買'], location: '名古屋市中區榮', mapQuery: '35.168909,136.906537', transport: '地鐵榮站直結', hours: '依各店面', cost: '免費（消費另計）', reservation: '❌', familyFriendly: '⭐⭐', rainFriendly: '✅ 全室內', weekendFriendly: '⚠️ 假日非常擁擠', notes: '可串連百貨、扭蛋店與餐廳，雨天也方便' },
  { name: '名古屋麵包超人兒童博物館＆公園', type: '兒童博物館・親子', categories: ['親子必去', '郊區一日遊'], location: '三重縣桑名市長島', mapQuery: '35.0307716,136.7307271', transport: '名古屋站搭巴士約50分', hours: '10:00–17:00', cost: '大人¥2200、小孩¥2200', reservation: '✅ 建議網路預約', familyFriendly: '⭐⭐⭐', rainFriendly: '⚠️ 室內外混合，雨天仍可玩但體驗打折', weekendFriendly: '⚠️ 假日非常擁擠，幼童難受', notes: '低幼親子熱門景點，可與長島 outlet 同天安排' },
  { name: '三井OUTLET PARK 爵士之夢長島', type: 'Outlet・購物', categories: ['購物採買', '郊區一日遊'], location: '三重縣桑名市長島', mapQuery: '35.030174,136.7254449', transport: '名古屋站搭巴士約50分', hours: '10:00–20:00', cost: '免費入場（消費另計）', reservation: '❌', familyFriendly: '⭐⭐', rainFriendly: '⚠️ 半戶外型 outlet，遇雨需撐傘', weekendFriendly: '⚠️ 假日人潮很多', notes: '品牌數量多，可與麵包超人館或長島渡假村同天' },
  { name: '犬山城', type: '城堡・歷史', categories: ['經典景點', '郊區一日遊'], location: '愛知縣犬山市', mapQuery: '35.3883604,136.9391766', transport: '名鐵犬山線 犬山遊園站 步行15分', hours: '09:00–17:00', cost: '大人¥550、小孩¥110', reservation: '❌', familyFriendly: '⭐⭐', rainFriendly: '⚠️ 天守閣室內OK，周邊露天', weekendFriendly: '⚠️ 假日人多，城下町擁擠', notes: '日本現存最古老天守閣之一' },
  { name: '博物館 明治村', type: '戶外博物館', categories: ['博物館', '郊區一日遊'], location: '愛知縣犬山市', mapQuery: '35.3404417,136.9885261', transport: '犬山站搭巴士約20分', hours: '09:30–17:00（依季節）', cost: '大人¥2000、小孩¥700', reservation: '❌', familyFriendly: '⭐⭐', rainFriendly: '❌ 戶外露天，下雨體驗很差', weekendFriendly: '✅ 假日OK，佔地廣不擁擠', notes: '明治建築移建保存，可與犬山城同天' },
  { name: '名古屋港水族館', type: '水族館', categories: ['親子必去', '動物／水族館'], location: '名古屋市港區', mapQuery: '35.09050879999999,136.8784377', transport: '地鐵名港線 名古屋港站 步行5分', hours: '09:30–17:30（週一休）', cost: '大人¥2030、小孩¥510', reservation: '⚠️ 假日早去', familyFriendly: '⭐⭐⭐', rainFriendly: '✅ 全室內', weekendFriendly: '⚠️ 假日非常擁擠，早點入場', notes: '虎鯨與海豚秀是亮點，雨天備案很好用' },
  { name: '名古屋 SEA LIFE 水族館', type: '水族館', categories: ['親子必去', '動物／水族館'], location: '名古屋市港區金城埠頭', mapQuery: '35.0503899,136.846351', transport: '青波線 金城埠頭站 步行5分', hours: '10:00–18:30', cost: '大人¥2200、小孩¥1100', reservation: '⚠️ 建議網路購票', familyFriendly: '⭐⭐⭐', rainFriendly: '✅ 全室內', weekendFriendly: '✅ 假日OK，比名古屋港水族館人少', notes: '就在樂高樂園旁邊，4/21 可接在 17:00 閉園後繼續逛到 18:30' },
  { name: 'TOYOTA 產業技術紀念館', type: '博物館・工業', categories: ['博物館'], location: '名古屋市西區', mapQuery: '35.182564,136.8759846', transport: '名鐵榮生站 步行3分', hours: '09:30–17:00（週一休）', cost: '大人¥500、小孩¥200', reservation: '❌', familyFriendly: '⭐⭐', rainFriendly: '✅ 全室內', weekendFriendly: '✅ 假日OK', notes: '紡織機到汽車工業的發展史展示很完整' },
  { name: '磁浮鐵道館', type: '博物館・交通', categories: ['親子必去', '博物館'], location: '名古屋市港區金城埠頭', mapQuery: '35.0491384,136.8509152', transport: '青波線 金城埠頭站 步行2分', hours: '10:00–17:30（週二休）', cost: '大人¥1000、小孩¥500', reservation: '❌', familyFriendly: '⭐⭐⭐', rainFriendly: '✅ 全室內', weekendFriendly: '✅ 假日OK', notes: '新幹線與磁浮列車實體展示，適合親子' },
  { name: '名古屋市科學館', type: '博物館・科學', categories: ['親子必去', '博物館'], location: '白川公園內', mapQuery: '35.1650768,136.8997026', transport: '地鐵伏見站 步行5分', hours: '09:30–17:00（週一休）', cost: '大人¥800、小孩¥500', reservation: '❌', familyFriendly: '⭐⭐⭐', rainFriendly: '✅ 全室內', weekendFriendly: '⚠️ 假日天象儀需搶票，建議早去', notes: '世界級球形天象儀是招牌，雨天非常適合' },
  { name: '波音博物館 FLIGHT OF DREAMS', type: '博物館・展覽', categories: ['博物館'], location: '中部國際機場內', mapQuery: '34.855313,136.8170461', transport: '中部國際機場站步行約5分', hours: '10:00–17:00', cost: '免費（部分設施收費）', reservation: '❌', familyFriendly: '⭐⭐', rainFriendly: '✅ 全室內', weekendFriendly: '✅ 假日OK', notes: 'Boeing 787 真機展示，適合抵達或離境日順遊' },
  { name: '長島渡假村', type: '遊樂園・溫泉', categories: ['親子必去', '郊區一日遊'], location: '三重縣桑名市長島', mapQuery: '35.0278358,136.7325592', transport: '名古屋站搭巴士約50分', hours: '10:00–17:00（依季節）', cost: '大人¥4800起、小孩¥3300起', reservation: '⚠️ 旺季建議網路購票', familyFriendly: '⭐⭐⭐', rainFriendly: '⚠️ 戶外設施多，小雨影響大', weekendFriendly: '⚠️ 假日非常擁擠，等待時間長', notes: '雲霄飛車、溫泉與購物設施一次滿足' },
  { name: 'JR名古屋高島屋 Gate Tower 購物中心', type: '購物・伴手禮', categories: ['購物採買'], location: '名古屋站直結', mapQuery: '35.1722068,136.8826178', transport: '名古屋站步行0分', hours: '10:00–20:00', cost: '免費入場（消費另計）', reservation: '❌', familyFriendly: '⭐⭐', rainFriendly: '✅ 全室內', weekendFriendly: '⚠️ 假日人多但OK', notes: '買 Piyorin 與名古屋土產很方便' },
];

export const creditCardData: CreditCardItem[] = [
  { name: '永豐 JCB', reward: '18.36%', bonusLimit: '2% 無上限 / 5% 上限 1000 / 刷 20300', condition: 'JCB 活動 10% 須刷滿 10 萬日圓', spendCap: '¥100000', notes: '飯店到店付款 86,192' },
  { name: '富邦 JCB', reward: '16%', bonusLimit: '3% 無上限 / 3% 上限 1000 / 刷 20300', condition: 'JCB 活動 10% 須刷滿 10 萬日圓', spendCap: '¥100000', notes: '餐食、購物' },
  { name: '中信 uniopen*2', reward: '11.0%', bonusLimit: '3% 無上限 / 8% 上限 500 / 刷 6250', condition: '實體卡消費', spendCap: '¥30800', notes: '日本 7-ELEVEN 單筆滿 1,500 日圓（含稅）享 225 日圓現金回饋' },
  { name: '永豐幣倍', reward: '6.0%', bonusLimit: '2% 無上限 / 4% 上限 800 / 刷 20000', condition: '實體卡消費', spendCap: '¥99000', notes: '—' },
  { name: '星展 eco', reward: '5.0%', bonusLimit: '1% 無上限 / 4% 上限 600 / 刷 15000', condition: '實體卡消費', spendCap: '¥74000', notes: '—' },
  { name: '永豐大戶*2', reward: '4.5%', bonusLimit: '2% 無上限 / 2.5% 上限 400 / 刷 16000', condition: '線上 / 實體皆可', spendCap: '¥79000', notes: 'Booking 線上付款 10,580 / 69,881' },
  { name: '台新 Richart', reward: '3.3%', bonusLimit: '無上限', condition: '線上 / 實體皆可', spendCap: '—', notes: '—' }
];

export const promoData: PromoItem = {
  title: '四月專屬！JCB 卡10% 回饋活動',
  subtitle: '這是四月出遊最值得搭配的限時活動！',
  period: '2026/2/1～2026/4/30（剛好可以用到）',
  condition: '在日本實體店消費累計滿 10 萬日幣（約 2 萬台幣）',
  reward: '10% 現金回饋，每卡上限 1 萬日幣',
  requirement: '需事先登錄（限 20 萬名，額滿即關閉），登錄前消費不算！',
  applicable: '任何台灣 JCB 信用卡（渣打 JCB 卡除外）'
};

export const ePayData: EPayItem[] = [
  { name: '全盈Pay', reward: '5.5% / 最高 13.5%', validity: '~2026/4/30', notes: '人人都有 5.5% 回饋，搭配彰化銀行帳戶最高 +8%' },
  { name: '全支付', reward: '3.5% / 最高 8.5%', validity: '~2026/6/30', notes: '筆筆 3.5% 無門檻，搭配國泰帳戶週回饋 +5%' },
  { name: '玉山 Wallet + 熊本熊卡', reward: '最高 5%', validity: '~2026/6/30', notes: 'PayPay 通路最高 5%' }
];
